framework:
    messenger:
        transports:
            kafka:
                dsn: "kafka://kafka:9092"
                serializer: App\Serializer\KafkaSerializer
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: orders
                    kafka_conf:
                        group.id: delivery-consumer
                        enable.auto.offset.store: 'false'
                    topic_conf:
                        auto.offset.reset: earliest

            kafka_publish:
                dsn: "kafka://kafka:9092"
                serializer: App\Serializer\KafkaSerializer
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: deliveries
                    kafka_conf:
                        group.id: delivery-publisher

        routing:
            'App\Message\OrderPlaced':       kafka
            'App\Message\DeliveryAssigned':  kafka_publish
            'App\Message\DeliveryCompleted': kafka_publish
